server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userMs
    username: root
    password: Sudeep@1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER_MS
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
 
  config:
    import: optional:configserver:http://localhost:8085
#        
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#      
#  instance:
#    prefer-ip-address: true
