server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingMs
    username: root
    password: Sudeep@1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  application:
    name: RATING_MS
  config:
    import: optional:configserver:http://localhost:8085


#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
    